### ISSUE TITLE
Please Provide More Documentation and example  of Venice

### ISSUE THREAD

**Issue by indrajitsinh** [Zewo/Venice#14]
thanks Venice u save my lot of time for writing code from scratch but  there is not very much documentation and example of Venice 

Documentation like what what class do ,what method do what about it what kind of parameter it takes what it return and a simple working  example of it 

it will be very helpful if you provide more documentation of Venice and Example of it

Thanks in advance
:+1:

**Comment by paulofaria** [comment]
We're going through a big refactor right now. But yes. When we're done this would be along our top priority. (:

**Comment by indrajitsinh** [comment]
don't be sad you guys doing great job :+1:  :)

**Comment by paulofaria** [comment]
Yeah, that's a smile facing the other way. like a smile in response. (: 
People always think it's a sad face haha.

**Comment by indrajitsinh** [comment]
ha ha ok 
let smily1 = (:
let smily2 = :)
 if smily1 == smily2
{ 
print ("both same \(smily1)"
}

ha ha funny :+1:

**Comment by paulofaria** [comment]
From now on we'll be tracking issues exclusively at https://github.com/Zewo/Zewo/issues ☺️
