### ISSUE TITLE
Dependency change in patch version

### ISSUE THREAD

**Issue by jdortiz** [Zewo/Venice#27]
Hi,
Thank you for all this work.
I have been trying to build https://github.com/necolt/Swifton-TodoApp which depends on your HTTPServer and, in turn, in Venice.
I couldn't build the product because I got a dependency graph error. I have tracked the issue to this package. In version 0.7.1 it depended on C7 0.7.x while in version 0.7.2, it depends on version 0.8.
The problem is that the dependencies on Venice  (HTTPServer->TCP->IP) are only targeting major and minor version, so there is no way to depend on C7 0.7.x as required by the other branch of packages. I can choose to go with 0.6.x or 0.8.x, none of which are valid for the other branch of packages.
In my opinion, based on the way that Swift Package Manager works now, you shouldn't change the dependencies on a patch version. Instead the change from C7 0.7.x to 0.8.x should happen only on Venice 0.8.0.
I think the only way to solve this is to create a new tag 0.7.3 from the 0.7.2 commit and revert the dependency on C7 to 0.7.x. The 0.8.x branch will stay as is and the issue would be resolved.
Please let me know if this isn't clear enough.

Best regards,

Jorge

**Comment by Danappelxx** [comment]
Hi! It's very unfortunate you ran into this issue. At Zewo we try to keep our tags synchronized, so when we updated to C7 0.8 and bumped our tags to 0.7, we also bumped the dependencies for Venice (which was already at 0.7). 

It looks like the Swifton example app got caught in a pocket in our dependency history where 0.7 was not yet stable and its dependencies shifted. Unfortunately, fixing this by reverting the 0.7.3 tag would mean breaking the rest of the v0.7 Zewo ecosystem, which depends on C7 0.8. The fix I suggest is for Swifton to bump its C7 dependency to 0.8 (mostly minor changes) and pushing a new release.

Sorry for the inconvenience.
