### ISSUE TITLE
Venice multi-threading

### ISSUE THREAD

**Issue by hartbit** [Zewo/Venice#7]
Can/does Venice use multiple CPU cores to execute coroutines in parallel? I can't seem to be able to get it working.

**Comment by paulofaria** [comment]
No. Venice depends on [libmill](https://github.com/sustrik/libmill). I asked Martin (the author of libmill) if he had plans for multi-threading support. This is his answer:

> Not really.
>
> First, black magic going on inside libmill may interact badly with pthreads (or it may not, it really depends on how pthreads are implemented).
> 
> Second, multithreading is a poor scalability strategy. You can scale until the number of threads is equal to number of cores and then you are stuck. You have to rewrite the entire application to scale across multiple machines.
> 
> What I was rather thinking of was providing an easy way to run multiple processes as a single application. Something that would act as better version of fork(). It could allow you run multiple processes (one per core or so) and multiplex incoming connections among them.
